### PR TITLE
change to libcmrt.pc from cmrt.pc since the .so name changed

### PR DESCRIPTION
**Pull request by guoyejun**

### CODE REVIEW

**Comment by jayesht** [comment]
intel_hybrid_driver fails to build with this pull request, and complains that: 

configure: error: Package requirements (cmrt >= 0.10.0) were not met:
No package 'cmrt' found

This happens as cmrt is now moved to libcmrt and thus dependency chain is broken for intel_hybrid_driver.

**Comment by guoyejun** [comment]
yes, someone else need to change intel_hybrid_driver  accordingly since i have no access on it.

actually, once the .so name is changed from cmrt.so to libcmrt.so, intel_hybrid_driver should have changed the link option from "-l:cmrt" to "-lcmrt", i guess.

to match the change of .so name, we'd better change the .pc name accordingly, and also change all the cmrt applications.

**Comment by chivakker** [comment]
Since the change will need to propagate to other library, is there other reason than  the name change to be made? I think we can stay with the current name

**Comment by guoyejun** [comment]
it is the 'standard' usage with file libname.pc, i guess. The sooner we changed to it, the less is impacted.  

If we decide to never change the file name later, i'll send another patch to only change the content of the file.

**Comment by gbeauchesne** [comment]
2015-10-13 2:43 GMT+02:00 guoyejun notifications@github.com:

> yes, someone else need to change intel_hybrid_driver accordingly since i
> have no access on it.
> 
> actually, once the .so name is changed from cmrt.so to libcmrt.so,
> intel_hybrid_driver should have changed the link option from "-l:cmrt" to
> "-lcmrt", i guess.
> 
> to match the change of .so name, we'd better change the .pc name
> accordingly, and also change all the cmrt applications.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/01org/cmrt/pull/24#issuecomment-147559113.

The correct changes are indeed:
- Let the DSO name be libcmrt.so.*, with the symlink being plain libcmrt.so
  ;
- Change intel_hybrid_driver link option from "-l:cmrt" to -lcmrt ;

## \- Have a pkg-config file called libcmrt.pc

Gwenole Beauchesne
Intel Corporation SAS / 2 rue de Paris, 92196 Meudon Cedex, France
Registration Number (RCS): Nanterre B 302 456 199

**Comment by guoyejun** [comment]
Beauchesne, my patch is exactly the same as your idea at CMRT side.

**Comment by gbeauchesne** [comment]
2015-10-13 10:29 GMT+02:00 guoyejun notifications@github.com:

> Beauchesne, my patch is exactly the same as your idea at CMRT side.

This is why I said this is "indeed what needs to be done". +1 if you
prefer. :)

**Comment by chivakker** [comment]
Yes I understand this is the standard and most libraries comply to it. To fix the problem, as you said, the users of the library have to be notified for them to fix accordingly. 

Knowing it is a mistake I also want to consider if leaving it alone would minimize the impact.

Until that happen I would prefer not to merge this patch

**Comment by seanvk** [comment]
@gbeauchesne,
Yes, this is on my list to do with the switch to libcmrt.  I'm glad Yejun submitted it.  I am entirely in agreement. I will also update the driver.  I also appreciate @chivakker 's concern.  However, hybrid use of CMRT requires a release tag which we use with Google's ebuild and we use with DPD's install script.  So all is cool.  
lgtm +2

**Pull request merged**
