### PR TITLE
Support dynamic loading

### PR DESCRIPTION
**Pull request by MidhunKodiyath**
Signed-off-by: Igor Chebykin igor.v.chebykin@intel.com
Signed-off-by: Mircea Gherzan mircea.gherzan@intel.com
Signed-off-by: Midhun Kodiyath midhunchandra.kodiyath@intel.com

### CODE REVIEW

**Comment by MidhunKodiyath** [comment]
QA testing for VPx use case is required.

**Comment by chivakker** [comment]
Can a commit message be added to the patch to understand who is dynamically loading cmrt?  It looked like the application that is loading cmrt has the requirement for all the renaming to add the _RT (run time) suffix to most classes and structures.

Can you provide also the use case that triggered this change?  It will help understand the scope of testing needed to happen for the Hybrid-driver.

Thanks.

**Comment by MidhunKodiyath** [comment]
Okay.I will take care of the Indentation in cm_rt.h.Thanks.

This for DPD's use cases.We need to cover our regular tests (mv_decoder_adv app and other regular tests) and make sure nothing has broken.
DPD already tested their use cases and it passed.

**Comment by srammohan** [comment]
On checking this patch, I found that there was segmentation fault at the end of the test execution even though the file generated matched the md5 value. 
I did not observe the seg fault  without the patch.

Error message:
Segmentation fault (core dumped)

Commands used for test:
$ mv_decoder_adv --vp9 -i ~/input/bitstreams/crowd_run_3840x2160@30_10000kbits.ivf -o ~/output/crowd_run_3840x2160@30_10000kbits.yuv --i420
$ mv_decoder_adv --vp9 -i ~/input/bitstreams/park_joy_50fps_w3840h2160.ivf  -o ~/output/park_joy_50fps_w3840h2160.yuv --i420

**Comment by MidhunKodiyath** [comment]
Okay..Thanks.
Looks like decoding is complete and seg fault is happening after that at the end.That is the reason why file generated matched the md5 value.
One strange thing observed is that without the patch also I saw a seg fault at the end using your samples on my setup.I will take a look and get back on this with a fix.

**Comment by seanvk** [comment]
Okay let me know when we need Rams to retest.

**Comment by MidhunKodiyath** [comment]
Can you please retest the latest changes? 
We need to cover our regular tests (mv_decoder_adv app and other regular tests) and make sure nothing has broken.Thanks..

**Comment by guoyejun** [comment]
i did a try and found more abstract classes are needed, for example CmSurface2D.

here is the build issue with out abstract class for CmSurface2D:
undefined reference to `CmSurface2D::WriteSurface(unsigned char const*, CmEvent*, unsigned long)'
undefined reference to`CmSurface2D::GetIndex(SurfaceIndex_&)'
undefined reference to `CmSurface2D::GetIndex(SurfaceIndex_&)'
undefined reference to `CmSurface2D::ReadSurface(unsigned char_, CmEvent_, unsigned long)'
collect2: error: ld returned 1 exit status

**Comment by MidhunKodiyath** [comment]
May I know what test you are running?

Scope of this patch is VPx test suite and DPDs use cases.This patch is very much limited to the DPDs requirement.They tested these changes with ~100% pass rate.Now we need to test vp9 decode use cases.I think Ram/Jayesh(QA) is going  cover vpx tests.

**Comment by guoyejun** [comment]
i just write a unit test myself, with the APIs exported in cm_rt.h, thanks.

**Comment by MidhunKodiyath** [comment]
I see.Thanks Guoyenjun.

I agree with you.We need to make CmSurface2D also abstract.I think it will helpful for future usecase and it's right thing to do.

**Comment by guoyejun** [comment]
i think there is another method to support dynamic loading. It doesn’t need to change current files inside cmrt, just add two files, one .h file for the c interface, the other .cpp file for the connection with cmrt c++ class.

The C interface looks like::
extern “C” INT CmDevice_LoadProgram(CmDevice\* pCmDev, 
    void *pCommonISACode, const UINT size,
                                                CmProgram \* &pProgram, const char *options)
{
                return pCmDev->LoadProgram(pCommonISACode, size, pPgogram, options);
}

And, yes, application has to use the new c functions if it want to dlopen/dlsym.

just for your reference

**Comment by anushasr** [comment]
Validated this patch. Looks good to me. It can be merged.

**Comment by seanvk** [comment]
We need to hold off on merge until we complete critical changes for Google.  We will merge next week.  Feel free to provide a drop to the folks needing it.  But I'm not ready to merge until we are in the clear on current Hybrid work.

**Comment by seanvk** [comment]
lgtm +2

**Pull request merged**
