### PR TITLE
Cilk+ offload library support

### PR DESCRIPTION
**Pull request by mgherzan**
This patch series contains a number of small fixes/cleanups as well as the support for abstract classes required by libgfxoffload.

### CODE REVIEW

**Comment by seanvk** [comment]
I will need this verified against your use cases as well as on vp9 hybrid decode.  I would prefer if someone other than yourself do the verification on your side.  I will have our QA verify Hybrid decode does not regress.

**Comment by srammohan** [comment]
I tried building the cmrt with this patch and the intel_hybrid_driver cloned from github and I find that there are linking issues in the hybrid driver that have been caused due to the changes in the CMRT driver. 
One of the linking error seen is:
vp9hdec/.libs/vp9hdec.a(vp9hdec_la-decode_hybrid_vp9.o): In function `Intel_HybridVp9Decode_MdfHost_SetKernelThreadCount(_INTEL_DECODE_HYBRID_VP9_MDF_ENGINE*, _INTEL_DECODE_HYBRID_VP9_MDF_FRAME*)':
/home/rams/vp9_decode/sources/intel-hybrid-driver/src/vp9hdec/decode_hybrid_vp9.cpp:1015: undefined reference to`CmKernel::SetThreadCount(unsigned int)'

This is caused as the class name has been changed from 'CmEvent' to 'CmEvent_RT' in <cmrt>src/cm_event.cpp

**Comment by mgherzan** [comment]
I have updated the patch series and I've tested that the intel_hybrd_driver builds with it.

**Comment by seanvk** [comment]
Hi Rams - Please retest based on updated patches.

**Comment by mgherzan** [comment]
Patch series updated once more with fixes for Cilk+ use cases.

**Comment by mgherzan** [comment]
Updated the last patch with more fixes/improvements suggested by Igor.

**Comment by jayesht** [comment]
Validated this pull request. Fails in hybrid driver decode.

Snippet: 
libva_info: Trying to open /usr/lib64/va/drivers/hybrid_drv_video.so
libva error: dlopen of /usr/lib64/va/drivers/hybrid_drv_video.so failed: /usr/lib64/va/drivers/hybrid_drv_video.so: undefined symbol: _ZN8CmDevice14DestroySurfaceERP11CmSurface2D
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

In our hybrid driver use case - we need cmrt library symbol defined upfront before opening the driver. Please re-look the commit.

**Comment by srammohan** [comment]
While validating the patch using Ubuntu, while executing the 'mv_decoder_adv' app, I get a segmentation fault with the patch. The dmesg shows the below mentioned error log:

mv_decoder_adv[21879]: segfault at 7fb85d32bbd0 ip 00007fb85d32bbd0 sp 00007ffc2fcf6858 error 15 in cmrt.so[7fb85d32b000+2000]

The segmentation fault is not seen without the patch.

**Comment by mgherzan** [comment]
Closing this pull request, as agreed with Midhun. A new pull request will be submitted for debugger support, once Cilk+ relevant patches are merged.

**Pull request closed without merging**
