### PR TITLE
Bump for new release

### PR DESCRIPTION
**Pull request by seanvk**

### CODE REVIEW

**Comment by chivakker** [comment]
lgtm :+1:

**Comment by seanvk** [comment]
@jayesht

**Comment by jayesht** [comment]
I verified this pull request on Ubuntu BSW and BDW platforms for VP9 decode.
I confirm that the webm/vp9 clips decoded fine with Yamidecode, and shows hybrid decode.

SKL validation is done with DPD tests. Summary: :Pass = 114, Fail 223, total =337

Patch LGTM for BSW/BDW and SKL Platforms.

**Comment by seanvk** [comment]
I removed the BXT enabling from this release to allow time for DPD team to debug their test code.

**Pull request merged**
