### PR TITLE
Enable BXT(APL)/KBL

### PR DESCRIPTION
**Pull request by wlin70**
Enable cmrt running on GPU of Broxton(Apollo Lake)/Kaby Lake.
Signed-off-by: Wei Lin wei.w.lin@intel.com

### CODE REVIEW

**Comment by seanvk** [comment]
We will need to test on KBL and APL.  
@jayesht  Can you test on both your KBL and APL systems?

Thanks,

Sean

**Comment by jayesht** [comment]
@wlin70 It would greatly help if you could list out tests to run to validate this pull request. Thanks.

**Comment by seanvk** [comment]
Test results look good via Wei.  Were you doing any additional tests @jayesht ?

**Comment by jayesht** [comment]
I have completed the validation on KBL. Will be starting on aplrvp tomorrow.

**Comment by wlin70** [comment]
This pull request sounds has been merge to 01org:master. 
To BXT test failure on GT type , I provided another pull request to fix it:  "https://github.com/01org/cmrt/pull/39" .  
I have done unit test on BXT.

**Comment by wlin70** [comment]
close it since has been merged.

**Pull request closed without merging**
