### PR TITLE
Shader Debugger Support

### PR DESCRIPTION
**Pull request by mgherzan**
The shader debugger support consists of:
1. Support for the system routine: the binary is requested from a debuggger interchange library and a STATE_SIP command is inserted in the batch buffer.
2. Debugger notification via the interchange library.
3. Shader debug mode activation via the "-debug" option.

This series contains the debugger-related patches on top of the "solid_build" ones, so https://github.com/01org/cmrt/pull/22 should be reviewed/merged first.

### CODE REVIEW

**Comment by seanvk** [comment]
Agree with @gbeauchesne, Please address.  I'll look at the rest later today.

**Comment by mgherzan** [comment]
Addressed in #22.

**Comment by seanvk** [comment]
This pull request mixes patches in pull request #22.  Please rebase and address.

**Comment by seanvk** [comment]
Please rebase.

**Comment by mgherzan** [comment]
Rebased as requested.

**Comment by seanvk** [comment]
Having QA do a run on #23

**Comment by seanvk** [comment]
@mgherzan QA is almost complete on test run.  Should have results later or tomorrow.

**Comment by igrche** [comment]
Patched OTC requires libigfxdbgxchg64.so.
Where I can download this library?

**Comment by igrche** [comment]
The gfx_sys_check utility from Intel compiler 16.0 fails to execute if there is no libigfxdbgxchg64.so in the LD_LIBRARY_PATH
Please note, that the utility does not use libgfxoffload.so offload runtime library.

So, the question is: 
Is it right that OTC CMRT with debugger support always needs the libigfxdbgxchg64.so ?

**Comment by mgherzan** [comment]
The OTC CMRT can run withouth the  libigfxdbgxchg64.so. This library is needed only when doing shader debugging.

**Comment by seanvk** [comment]
final patch series lgtm and have now been verified by compiler and qa teams

**Pull request merged**
