### PR TITLE
Generic fixes and EU debugger support.

### PR DESCRIPTION
**Pull request by mgherzan**
Various fixes to improve the quality of the code, enable debug builds and support the GDB-based shader debugger.

### CODE REVIEW

**Comment by seanvk** [comment]
@MidhunKodiyath PTAL

**Comment by mgherzan** [comment]
Will split into 2 series.

**Comment by srammohan** [comment]
Getting build failures on CMRT pulling the patch. 
Probably needs rebase and patch submission.

**Comment by mgherzan** [comment]
Please take a look at https://github.com/01org/cmrt/pull/22 first.

If you really want to test the debugger feature, please use the "debugger" branch from my repo.

**Pull request closed without merging**
