### PR TITLE
Shader debug support for Broadwell and Skylake

### PR DESCRIPTION
**Pull request by mgherzan**
Shader debugging needs to be enabled via MMIO registers.

Signed-off-by: Mircea Gherzan mircea.gherzan@intel.com

### CODE REVIEW

**Comment by seanvk** [comment]
Jayesh will verify.

**Comment by jayesht** [comment]
Hi Mircea,
   I would appreciate if you could help me with the typical tests that you would like me to run on this pull request as part of verification.
Thanks.

**Comment by mgherzan** [comment]
Jayesh, please run the "hybrid" manual tests. Sean can provide details
about them.

**Comment by seanvk** [comment]
Jayesh - please retest with updated patches.

**Comment by jayesht** [comment]
Picking up updated commit and validating on SKL and BDW.

**Comment by seanvk** [comment]
Thanks @jayesht

**Comment by jayesht** [comment]
Validated the pull request#31 with
1.  script for vp9_hybrid_decode_script_libyami on BDW and SKL platform, it validates md5sum of decoded bitstreams. 
2. Manual yamidecode run for VP9 stress bitstreams, on screen and to the file decode runs.

On side note: yamidecode shows Red colorspace output with BDW, whereas shows Gray colorspace output on SKL. This is yamidecode's issue.

Patch lgtm.

**Comment by seanvk** [comment]
Thanks all, merged.

**Pull request merged**
