### PR TITLE
Fix and improve the debug build

### PR DESCRIPTION
**Pull request by mgherzan**
The goal of this series is to have a debug library (i.e. _DEBUG macro defined => assertions enabled) that can be built warning-free with contemporary compilers (Clang 3.7, GCC 5+)

### CODE REVIEW

**Comment by seanvk** [comment]
Please rebase.  Also, will need to have QA validate.

**Comment by MidhunKodiyath** [comment]
Yes.This needs to be re-based and tested using DPD's use cases first.
Looks like "Fix the case statements in IntelGen_GetPixelsPerSample()" patch needs to be removed
since its already been resolved in the master.

**Comment by mgherzan** [comment]
Rebased as suggested.

**Comment by mgherzan** [comment]
Removed the "Fix the case statements in IntelGen_GetPixelsPerSample()" patch as suggested.

**Comment by MidhunKodiyath** [comment]
It gives core dump at the end of the vpx run/execution on my setup.
 Aborted (core dumped).
This issue could be intoduced by "Fix the debug build" or "Fix the SurfaceIndex class".Not sure though.Please take a look.

**Comment by mgherzan** [comment]
I do not have the the VPx test binaries. Can you please run this test case under GDB and provide a backtrace at the point of the abort? Most likely it's an assertion failure.

**Comment by MidhunKodiyath** [comment]
Like I said "Fix the debug build" is introducing the issue.I reverted this and test passed."Fix the debug build" is a part of debugger changes and I think its better to add this commit to your debugger pull request or request for a sperate pull request.More debugging is required on this.
Lets test ,review and merge other set of patches which is not depended on it..!

**Comment by mgherzan** [comment]
The "Fix the debug build" is the most important patch in this series and it has _nothing_ to do with the shader debugger. So it does not belong to the debugger pull request.

"Fix the debug build" is about enabling the CMRT to build with the _DEBUG macro defined, which enables assertions. Most likely the abort is caused by an assert() being triggered.

So please use GDB to get a stack trace at the moment of the abort and please share the VPx test cases so I can reproduce/investigate this.

**Comment by MidhunKodiyath** [comment]
Okay.You probably need to debug yourself and fix this.Also please add a short description of the patch.

Ram,Please share the vpx test case binaries if possible.

**Comment by seanvk** [comment]
Agree with @MidhunKodiyath, we will need @mgherzan to debug and fix this issue reported.

**Comment by mgherzan** [comment]
I've removed -Werror from the CFLAGS as suggested by @gbeauchesne .

I am still waiting for the test cases/binaries so I can debug and fix this...

In the meantime, @MidhunKodiyath, can you please comment out the abort() call in os_util_debug.c line 106 and retest? This will give us a a better picture o the issue.

**Comment by seanvk** [comment]
@srammohan

Please update with test case/binaries.  You can share with @mgherzan through Gdrive.

**Comment by mgherzan** [comment]
With the new patch ("Fix the array handling..."), the VPx test cases are passing on my Ubuntu BDW setup. As expected, this patch series did not cause a new isseu, it was merely pointing out an issue in the existing code.

Please resume the review and testing process as soon as possbile. Thanks!

**Comment by seanvk** [comment]
@srammohan Please continue the testing.

**Comment by seanvk** [comment]
approved.  lgtm +2.

**Comment by srammohan** [comment]
Validated the patch by running the VP9 decode script. 95 out of 108 tests passed.

**Comment by igrche** [comment]
1) Patched OTC requires libigfxdbgxchg64.so.
Where I can download this library?

2) The gfx_sys_check utility from Intel compiler 16.0 failed if there is no libigfxdbgxchg64.so in the LD_LIBRARY_PATH
Please note, that the utility does not use libgfxoffload.so offload runtime library.

So, the question is: 
Is it right that OTC CMRT with debugger support always needs the libigfxdbgxchg64.so ?

**Pull request merged**
