### PR TITLE
BXT's GT Type Recognition

### PR DESCRIPTION
**Pull request by wlin70**
Recognize BXT's GT Type.

Signed-off-by: Wei Lin wei.w.lin@intel.com

### CODE REVIEW

**Comment by seanvk** [comment]
@jayesht  Please re-verify with this addition.

**Comment by seanvk** [comment]
@jayesht can you update me on this verification?  @chivakker FYI

**Comment by jayesht** [comment]
I validated pull request#39 on aplrvp.

Summary:
96 Pass 238 Fail. 334 total
Most failures are due to lacks of “AVX” instruction.

logs are shared with @wlin70

**Comment by wlin70** [comment]
@seanvk I suggest to merge #39 if BXT is decided to be supported. 
Due to current test result,  basic driver function well,   and the failure are test cases issue (like optimized with AVX inst. not existing in BXT) or jitter bugs.

**Comment by seanvk** [comment]
agree @wlin70 merged.

**Pull request merged**
