### PR TITLE
add support for SKL platform

### PR DESCRIPTION
**Pull request by lsun30**
Signed-off-by: Lina Sun lina.sun@intel.com

### CODE REVIEW

**Comment by yakuizhao** [comment]
This looks good to me.

**Comment by lsun30** [comment]
I have renamed two files and removed some unused lines of code following Wei's comments.

**Comment by wlin70** [comment]
It is fine to me.

**Comment by srammohan** [comment]
Validated the patch on Ubuntu 15.04 with the hybrid driver installed. I was able to generate the decoded content to a file and able to play using ffplay but I was not able to play it on the screen using yamidecode.

**Comment by seanvk** [comment]
lgtm.  Less worried about screen issue.

**Pull request merged**
